version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smarttrip
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=smarttrip
      - JWT_SECRET=supersecret
      - EMAIL_USER=dummy@example.com
      - EMAIL_PASS=dummypassword
      - WEATHER_API_KEY=dummykey
      - EVENT_API_KEY=dummykey
      - OPENAI_API_KEY=dummykey
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    volumes:
      - ./frontend:/app

volumes:
  db-data:
